# replace this with correct path
import = ["/home/mau/.config/alacritty/nord.toml"]
live_config_reload = true

[shell]
program = "/bin/fish"
args = ["-l", "-c", "tmux attach || tmux"]

[window]
startup_mode = "Windowed"
opacity = 0.90

[window.padding]
x = 0
y = 0

[window.position]
x = 25
y = 75

[window.dimensions]
columns = 150
lines = 40

[scrolling]
history = 10_000
multiplier = 10

[font]
size = 20

[font.normal]
family = "ShureTechMono Nerd Font"

[font.glyph_offset]
x = 0
y = 0

[mouse]
hide_when_typing = true
# save_to_clipboard = true

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[cursor]
style = "Block"
unfocused_hollow = true

[debug]
render_timer = false
persistent_logging = false
log_level = "Warn"
print_events = false
# ref_test = false

[keyboard]
bindings = [
  { key = "Return", mods = "Alt", action = "ToggleFullscreen" },
  { key = "K", mods = "Command", action = "ClearHistory" },
  { key = "V", mods = "Command", action = "Paste" },
  { key = "C", mods = "Command", action = "Copy" },
  { key = "Right", mods = "Alt", chars = "\u001bF" },
  { key = "Left", mods = "Alt", chars = "\u001bB" },
  { key = "Back", mods = "Command", chars = "\u0015" },
]
