import = [ "C:\\Users\\mhern\\AppData\\Roaming\\alacritty\\nord.yml" ]
draw_bold_text_with_bright_colors = true
live_config_reload = true

[shell]
program = "wsl -d Ubuntu-20.04"

[window]
decorations = "full"
startup_mode = "Windowed"
opacity = 0.9

  [window.padding]
  x = 0
  y = 0

  [window.position]
  x = 25
  y = 75

  [window.dimensions]
  columns = 150
  lines = 40

[scrolling]
history = 10_000
multiplier = 10

[font]
size = 16

  [font.normal]
  family = "Hurmit Nerd Font Mono"

  [font.glyph_offset]
  x = 0
  y = 0

[mouse]
hide_when_typing = true
save_to_clipboard = true

  [mouse.selection]
  semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[cursor]
style = "Block"
unfocused_hollow = true

[debug]
render_timer = false
persistent_logging = false
log_level = "Warn"
print_events = false
ref_test = false

[[key_bindings]]
key = "Return"
mods = "Alt"
action = "ToggleFullscreen"

[[key_bindings]]
key = "K"
mods = "Command"
action = "ClearHistory"

[[key_bindings]]
key = "V"
mods = "Command"
action = "Paste"

[[key_bindings]]
key = "C"
mods = "Command"
action = "Copy"

[[key_bindings]]
key = "Right"
mods = "Alt"
chars = "\u001bF"

[[key_bindings]]
key = "Left"
mods = "Alt"
chars = "\u001bB"

[[key_bindings]]
key = "Back"
mods = "Command"
chars = "\u0015"
