[colors.primary]
background = "#090713"
foreground = "#d8dee9"
dim_foreground = "#a5abb6"

[colors.cursor]
text = "#2e3440"
cursor = "#d8dee9"

[colors.vi_mode_cursor]
text = "#2e3440"
cursor = "#d8dee9"

[colors.selection]
text = "CellForeground"
background = "#4c566a"

[colors.search.matches]
foreground = "CellBackground"
background = "#88c0d0"

[colors.footer_bar]
background = "#434c5e"
foreground = "#d8dee9"

[colors.normal]
black = "#3b4252"
red = "#bf616a"
green = "#a3be8c"
yellow = "#ebcb8b"
blue = "#819be5"
magenta = "#b48ead"
cyan = "#88c0ef"
white = "#e5e9ff"

[colors.bright]
black = "#4c566a"
red = "#ef616a"
green = "#a3be8c"
yellow = "#ebcb8b"
blue = "#818bf5"
magenta = "#b48ead"
cyan = "#8fbcbb"
white = "#fcfcff"

[colors.dim]
black = "#373e4d"
red = "#94545d"
green = "#809575"
yellow = "#b29e75"
blue = "#68809a"
magenta = "#8c738c"
cyan = "#6d96a5"
white = "#aeb3bb"

